---
title: Gin -- Default 404 handler
---



> 当handler不存在时，需要定义默认handler的处理行为，默认Gin返回值为“404 page not found”。但通常我们需要自定义错误符合返回规范。



以下是自定义错误的示例：

```go
	// Set up No Route
	r.Engine.NoRoute(func(c *gin.Context) {
		errno.GinJSONResponseErr(c, errno.ErrorNotFoundAPI())
	})
```



其中ErrorNotFoundAPI是统一封装的自定义错误：

```
// APIExceptions
type APIException struct {
	Code      int    `json:"-"`
	ErrorCode int    `json:"errorCode"`
	Msg       string `json:"message"`
}

func (e *APIException) Error() string {
	return e.Msg
}
func newAPIException(code int, errorCode int, msg string) *APIException {
	return &APIException{
		Code:      code,
		ErrorCode: errorCode,
		Msg:       msg,
	}
}

const (
  ...
  ErrNotFoundAPI       = 20205 // API NotFound
  ...
)

func ErrorNotFoundAPI() *APIException {
	return newAPIException(http.StatusNotFound, ErrNotFoundAPI, "API Not Found")
}

// Resonse Gin JSON With Error
func GinJSONResponseErr(c *gin.Context, e *APIException) {
	GinJSONResponse(c, e.Code, e)
}

// Resonse Gin JSON With Interface
func GinJSONResponse(c *gin.Context, code int, i interface{}) {
	c.JSON(code, i)
}
```



此时访问一个不存在的URL时404返回类似如下：

```
➜  ~ curl https://api.dev.pano.video/gslb/abc/abc
{"errorCode":20205,"message":"API Not Found"}
```



